name: Update Homebrew Formula & Cask

on:
  workflow_call:
    inputs:
      update_cli:
        description: 'Whether to update the CLI formula'
        required: false
        type: boolean
        default: false
      update_mac:
        description: 'Whether to update the macOS app cask'
        required: false
        type: boolean
        default: false
    secrets:
      brew_tap_token:
        description: 'PAT with permissions to push to homebrew-susops'
        required: true

jobs:
  release-version-check:
    runs-on: ubuntu-latest
    outputs:
      is_prerelease: ${{ steps.check.outputs.is_prerelease }}
    steps:
      - name: Check for release tag
        id: check
        shell: bash
        run: |
          TAG="$GITHUB_REF_NAME"
          # Match only X.Y.Z (no prerelease or build metadata)
          if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          fi

  update:
    needs: release-version-check
    if: ${{ needs.release-version-check.outputs.is_prerelease == 'false' && (inputs.update_mac || inputs.update_cli) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out tap repo
        uses: actions/checkout@v4
        with:
          repository: mashb1t/homebrew-susops
          token: ${{ secrets.brew_tap_token }}
          path: homebrew-susops
          persist-credentials: true

      # CLI update steps
      - name: Fetch latest CLI release
        if: ${{ inputs.update_cli }}
        id: cli
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: "mashb1t/susops-cli"

      - name: Compute CLI SHA & version
        if: ${{ inputs.update_cli }}
        id: cli_sha
        run: |
          RAW_CLI_VER=${{ steps.cli.outputs.release }}
          CLI_VER=${RAW_CLI_VER#v}
          CLI_SHA=$(curl -L https://github.com/mashb1t/susops-cli/archive/refs/tags/${RAW_CLI_VER}.tar.gz | shasum -a 256 | awk '{print $1}')
          echo "CLI_SHA=$CLI_SHA" >> $GITHUB_OUTPUT
          echo "CLI_VER=$CLI_VER" >> $GITHUB_OUTPUT

      # macOS App update steps
      - name: Fetch latest macOS App release
        if: ${{ inputs.update_mac }}
        id: mac
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: "mashb1t/susops-mac"

      - name: Compute Cask SHA & version
        if: ${{ inputs.update_mac }}
        id: mac_sha
        run: |
          RAW_MAC_VER=${{ steps.mac.outputs.release }}
          MAC_VER=${RAW_MAC_VER#v}
          MAC_SHA=$(curl -L https://github.com/mashb1t/susops-mac/releases/download/v${MAC_VER}/SusOps.zip | shasum -a 256 | awk '{print $1}')
          echo "MAC_SHA=$MAC_SHA" >> $GITHUB_OUTPUT
          echo "MAC_VER=$MAC_VER" >> $GITHUB_OUTPUT

      # Update Formula
      - name: Update Formula/susops.rb
        if: ${{ inputs.update_cli }}
        working-directory: homebrew-susops
        run: |
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.cli_sha.outputs.CLI_SHA }}\"|" Formula/susops.rb
          sed -i "s|version \".*\"|version \"${{ steps.cli_sha.outputs.CLI_VER }}\"|" Formula/susops.rb

      # Update Cask
      - name: Update Casks/susops.rb
        if: ${{ inputs.update_mac }}
        working-directory: homebrew-susops
        run: |
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.mac_sha.outputs.MAC_SHA }}\"|" Casks/susops.rb
          sed -i "s|version \".*\"|version \"${{ steps.mac_sha.outputs.MAC_VER }}\"|" Casks/susops.rb

      - name: Commit bump
        uses: EndBug/add-and-commit@v9
        with:
          cwd: homebrew-susops
          author_name: github-actions
          author_email: actions@github.com
          message: >-
            ci: bump
            ${{ inputs.update_cli && inputs.update_mac && 'formula & cask'
              || inputs.update_cli && 'formula'
              || inputs.update_mac && 'cask' }}
            to ${{ inputs.update_cli && steps.cli_sha.outputs.CLI_VER || '' }}
            ${{ inputs.update_cli && inputs.update_mac && '/' || '' }}
            ${{ inputs.update_mac && steps.mac_sha.outputs.MAC_VER || '' }}
          add: |
            Formula/susops.rb
            Casks/susops.rb
